#Create new droplet
---

# Ensure SSH Key is present, else upload provided --
- hosts: 127.0.0.1
  connection: local
  #serial: 1
  gather_facts: False

  roles:
  - do-droplet

  vars:
    api_key: "{{ lookup('env','DIGITALOCEAN_API_KEY') }}"
    client_id: "{{ lookup('env','DIGITALOCEAN_CLIENT_ID') }}"
    my_pub_key: "{{ lookup('file', '/Users/tripl3inf/.ssh/digitalOcean.pub') }}"
    ssh_key_name: master
    do_hostname: tripl3inf.com
    #do_admin: tripl3inf
    image_id: 7111343 #ubuntu 14.10
    region_id: 8 #nyc3

# When new droplet is ready, provision
- hosts: new_drops
  gather_facts: True
  remote_user: root
  #sudo: true

  roles:
  - user
  - apps

  vars:
    my_pub_key: "{{ lookup('file', '/Users/tripl3inf/.ssh/digitalOcean.pub') }}"

  vars_prompt:
  - name: "deploy_user"
    prompt: "Enter a user name"
    private: no

  - name: "deploy_user_email"
    prompt: "Enter admin email address"
    private: no

  - name: "deploy_passwd"
    prompt: "Enter a new password for the user"
    private: yes
    encrypt: "md5_crypt" #need to have python-passlib installed in local machine before we can use it
    confirm: yes
    salt_size: 7

