---
- name: "Setup WP - {{env}}"
  hosts: all
  remote_user: "{{ deploy_user }}"
  #sudo: true
  sudo_user: root

  tasks:
    - include: roles/wordpress/tasks/structure.yml
    - include: roles/wordpress/tasks/db.yml
    - include: roles/wordpress/tasks/nginx.yml
    - include: roles/wordpress/tasks/php-fpm.yml
    - include: roles/wordpress/tasks/wp.yml
    - include: roles/wordpress/tasks/theme.yml
    - include: roles/debug/tasks/webgrind.yml
  vars:
    env: staging
    wp_project_name: t3inf ### TODO: change mysql db user from project name -- messes up if puctuation is used
    wp_home_url: t3inf.dev
    wp_db_name: DB_t3inf_dev
    wp_db_pass: tripl3World!
    wp_admin_pass: tripl3World!
    theme_name: roots
    theme_repo_url: git@github.com:roots/roots.git

  handlers:
    - include: roles/wordpress/handlers/main.yml
