#  __      __          _                      ___ _           _            _
#  \ \    / /__ _ _ __| |_ __ _ _ ___ ______ | _ \ |__ _ _  _| |__ ___ ___| |__
#   \ \/\/ / _ \ '_/ _` | '_ \ '_/ -_)_-<_-< |  _/ / _` | || | '_ \ _ \ _ \ / /
#    \_/\_/\___/_| \__,_| .__/_| \___/__/__/ |_| |_\__,_|\_, |_.__\___\___/_\_\
#                       |_|                              |__/

- name: Initiate Wordpress project...
  hosts: all
  remote_user: "{{deploy_user}}"
  sudo_user: root
  vars:
    deploy_user: tripl3inf
    sql_root_pass: sql_pass
    project:
      name: t3inf ### TODO: change mysql db user from project name -- messes up if punctuation is used
      env: dev # convention = dev,staging,prod
      home_url: t3inf.com # NO sub-domain -- eg: google.com, not www.google.com
      db_pass: tripl3World!
      admin_pass: tripl3World!
      admin_email: tripl3infinity@gmail.com
      auto_update: no
      theme:
        name: custom
        url: 'git@github.com:tripl3inf/WordPlay-Theme.git'
        branch: t3inf
      vbox: false
      memcached_sessions: false
  tasks:
    - include: roles/wordpress/tasks/main.yml
    - include: roles/wordpress/tasks/dev.yml
      when: project.env == 'dev'
      sudo: false
    - include: roles/wordpress/tasks/deploy.yml
      when: project.env != 'dev'

  handlers:
    - include: roles/wordpress/handlers/main.yml

