---
- hosts: 127.0.0.1
  connection: local
  #serial: 1
  gather_facts: False
  roles:
  - do-droplet
  vars:
    api_key:
    client_id:
    my_pub_key: "{{ lookup('file', '~/.ssh/t3i_deploy.pub') }}"
    do_hostname: t3inf.com
    do_admin: tripl3inf
    image_id: 6510539
    region_id: 8

- hosts: new_drops
  gather_facts: True
  vars_prompt:
  - name: "deploy_user"
    prompt: "Enter a user name"
    private: no

  - name: "deploy_passwd"
    prompt: "Enter a new password for the user"
    private: yes
    encrypt: "md5_crypt" #need to have python-passlib installed in local machine before we can use it
    confirm: yes
    salt_size: 7
  remote_user: root
  #sudo_user: root
  #sudo: true

  ### Override the defaults included in user role
  vars:
    sudoers_email: true
    deploy_group: t3i
  roles:
  - user
  - apps

