---
- name: " Initiate Wordpress project -- {{project.env}} @ {{ ansible_hostname }} "
  hosts: all
  remote_user: "{{ deploy_user }}"
  #sudo: true
  sudo_user: root
  tasks:
    - include: roles/wordpress/tasks/main.yml
    - include: roles/wordpress/tasks/deploy.yml
  vars:
    deploy_user: tripl3inf
    sql_root_pass: sql_pass
    project:
      name: t3inf ### TODO: change mysql db user from project name -- messes up if punctuation is used
      env: prod # convention = dev,staging,prod
      home_url: t3inf.com
      db_pass: tripl3World!
      admin_pass: tripl3World!
      admin_email: tripl3infinity@gmail.com
      auto_update: no
      theme:
        name: roots
        url: 'git@github.com:tripl3inf/WordPlay-Theme.git'
        branch: feat_logoAnimation
      vbox: false
      memcached_sessions: false
  handlers:
    - include: roles/wordpress/handlers/main.yml

