#    ___              _         ___  _      _ _        _  ___                     ___               _     _
#   / __|_ _ ___ __ _| |_ ___  |   \(_)__ _(_) |_ __ _| |/ _ \ __ ___ __ _ _ _   |   \ _ _ ___ _ __| |___| |_
#  | (__| '_/ -_) _` |  _/ -_) | |) | / _` | |  _/ _` | | (_) / _/ -_) _` | ' \  | |) | '_/ _ \ '_ \ / -_)  _|
#   \___|_| \___\__,_|\__\___| |___/|_\__, |_|\__\__,_|_|\___/\__\___\__,_|_||_| |___/|_| \___/ .__/_\___|\__|
#                                     |___/                                                   |_|
# DEPENDENCIES:
#   - DOPY Module (pip install dopy)
#   - python-passlib (apt-get install)


---
# Ensure SSH Key is present, else upload provided --
- hosts: 127.0.0.1
  connection: local
  gather_facts: False

  roles:
  - do-droplet

  vars:
    api_key: "{{ lookup('env','DIGITALOCEAN_API_KEY') }}"
    client_id: "{{ lookup('env','DIGITALOCEAN_CLIENT_ID') }}"
    my_pub_key: "{{ lookup('file', '/Users/tripl3inf/.ssh/digitalOcean.pub') }}"
    ssh_key_name: master
    do_hostname: tripl3inf.com
    image_id: 7111343 #ubuntu 14.10
    region_id: 8 #nyc3

# When new droplet is ready, provision
- hosts: new_drops
  gather_facts: True
  remote_user: root

  roles:
  - user
  - apps
  - env_vars

  vars:
    my_pub_key: "{{ lookup('file', '/Users/tripl3inf/.ssh/digitalOcean.pub') }}"

  vars_prompt:
  - name: "deploy_user"
    prompt: "Enter a user name"
    private: no

  - name: "deploy_user_email"
    prompt: "Enter admin email address"
    private: no

  - name: "deploy_passwd"
    prompt: "Enter a new password for the user"
    private: yes
    encrypt: "md5_crypt"
    confirm: yes
    salt_size: 7

