---
- name: Fetch random salts for Wordpress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
  sudo: false
  tags: dbg

- name: Create wp-config file
  template: src="template_wp-config.php" dest="{{project_path.stdout}}/www/wp-config.php"
  register: "{{project.env}}"

- name: Copy index.php file
  template: src="template_wp_index.php" dest="{{project_path.stdout}}/www/index.php"


