---
- name: Create database of sites
  mysql_db: name="{{ project.env | default(prod) }}_{{ project.name }}"
            state=present
            login_host="localhost"
            login_user=root
            login_password="{{ sql_root_pass }}"
  sudo: true

- name: Create/assign database user to db and grant permissions
  mysql_user: name="{{ deploy_user }}"
              password="{{ project.db_pass }}"
              priv=*.*:ALL
              state=present
              login_host="localhost"
              login_user=root
              login_password="{{ sql_root_pass }}"
  sudo: true

#priv="{{ project.env | default(prod) }}_{{ project.name }}.*:ALL"
