---
- name: Install WP
  command: wp core install
           --allow-root
           --url="{{ project.home_url }}"
           --title="{{ project.name }}"
           --admin_user="{{ deploy_user }}"
           --admin_password={{ project.admin_pass }}
           --admin_email={{ project.admin_email }}
           --path=wordpress
  args:
    chdir: "{{project_path.stdout}}/www"

#- name: Copy stock themes
#  shell: "cp -r {{project_path.stdout}}/www/wordpress/wp-content/themes/* {{project_path.stdout}}/www/content/themes/"
#  notify:
#    - restart php-fpm
#    - restart nginx

