---
- name: Install WP
  command: wp core install
           --allow-root
           --url="{{ project.home_url }}"
           --title="{{ project.name }}"
           --admin_user="{{ deploy_user }}"
           --admin_password="{{ project.admin_pass }}"
           --admin_email="{{ project.admin_email }}"
           --path="wordpress"
  args:
    chdir: "{{project_path.stdout}}"
  #when: wp_core_files | changed
  notify: restart nginx


#- name: Symlink stock themes
#  file: src={{project_path.stdout}}/wordpress/wp-content/themes
#        dest={{project_path.stdout}}/content/themes
#        owner=root
#        group=root
#        state=link
