# create directory structure
- include: structure.yml
  sudo: true

# create database
- include: db.yml

# add Nginx conf
- include: nginx.yml
  tags: nginx

# add PHP-FPM conf
- include: php-fpm.yml

# configure wordpress
- include: wp.yml

## configure theme building environment
#- include: theme.yml
#  tags: theme

## Staging
#- include: structure.yml env=staging
#  sudo: true
#  tags: staging
#
#- include: db.yml env=staging
#  sudo: true
#  tags: staging
#
#- include: nginx.yml env=staging
#  sudo: true
#  tags: staging
#
#- include: php-fpm.yml env=staging
#  sudo: true
#  tags: staging
#
#- include: wp.yml env=staging
#  sudo: true
#  tags: staging
#
#- include: theme.yml env=staging
#  sudo: true
#  tags: staging
