---
 - name: Create WordPress configuration for Nginx
   template: src="template_nginx_wp.conf" dest={{ngx_conf.stdout}}
   sudo: true

 - name: Add sendfile off param if VBox ( http://wiki.nginx.org/Pitfalls )
   lineinfile: dest=ngx_conf insertafter="^listen" line="sendfile off;"
   when: 'project.vbox == true'


