---
- name: Create projects site root
  file: path={{project_path.stdout}}
        state=directory
  sudo: true

- name: Create project directory structure
  file: path={{project_path.stdout}}/{{item}}
        state=directory
  with_items:
    - logs
    - repo
  sudo: true

- name: Set permisions on project env
  file: path={{project_path.stdout}}
        state=directory
        recurse=yes
        mode=0777
  sudo: true
