---

- name: Register theme directory
  command: "echo /srv/{{project.env}}/{{ project.name }}/content/themes"
  register: theme_path

- name: Create WP theme directory
  file: path={{theme_path.stdout}}
        state=directory
        mode=0775
  register: theme

#- debug: var=content_path.path

- name: Checkout theme base from REPO
  git: repo={{project.theme.url}} dest={{theme_path.stdout}}/{{project.theme.name}}
       accept_hostkey=yes
       force=yes
       version=outside
  sudo: false
#  sudo_user: "{{ deploy_user }}"


- name: Build theme
  shell: cd {{theme_path.stdout}}/{{project.theme.name}}; {{ item }}
  ignore_errors: true
  with_items:
    - npm install
    - bower install --silent
    - grunt build
  sudo: true
  notify: restart php-fpm

- name: Wait to restart nginx
  pause: seconds=10
  notify: restart nginx




#- name: NPM install
#  npm: path=content_path.stdout/themes/ten10_roots
#       state=present
#
#- name: Bower install
#  shell: cd content_path.stdout/themes/ten10_roots; bower install --silent
#
#- name: Grunt build
#  shell: cd content_path.stdout/themes/ten10_roots; grunt build

