---
- name: Register project path
  command: "echo /srv/{{env}}/{{wp_project_name}}"
  register: project_path
  tags: dbg

- name: Fetch random salts for Wordpress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
  sudo: false
  tags: dbg

- name: Create wp-config file
  template: src="template_wp-config.php" dest="{{project_path.stdout}}/wp-config.php"
  sudo: false
  register: "{{env}}"
  tags: dbg

- name: Copy index.php file
  template: src="template_wp_index.php" dest="{{project_path.stdout}}/index.php"
  sudo: false

- name: Download WP core files
  command: wp core download --path="{{project_path.stdout}}/wordpress/"
  sudo: false
  ignore_errors: true
  register: wp_core_files

- name: WP installed?
  command: wp core is-installed --allow-root
  args:
    chdir: "{{project_path.stdout}}/wordpress"
  when: wp_core_files | changed
  register: site_status
  ignore_errors: true

- name: Install WP
  command: wp core install
           --allow-root
           --url="{{ wp_home_url }}"
           --title="{{ wp_project_name }}"
           --admin_user="{{ deploy_user }}"
           --admin_password="{{ wp_admin_pass }}"
           --admin_email="{{ wp_admin_email }}"
           --path="wordpress"
  args:
    chdir: "{{project_path.stdout}}"
  when: wp_core_files | changed
  #notify: restart nginx

#- name: Wait to restart php-fpm
#  pause: seconds=10
#  notify: restart php-fpm

