---
 - name: Register Nginx configuration file name
   command: "echo {{ env | default(prod) }}_{{ wp_project_name }}.conf"
   register: config

 - debug: vars=config.stdout

 - name: Create WordPress configuration for Nginx
   template: src="template_nginx_wp.conf" dest=/etc/nginx/sites-available/{{config.stdout}}
   #ignore_errors: true
   sudo: true

 - name: Add sendfile off param if VBox ( http://wiki.nginx.org/Pitfalls )
   lineinfile: dest=config insertafter="^listen" line="sendfile off;"
   when: VBox

 - name: Enable WordPress site
   file: src=/etc/nginx/sites-available/{{config.stdout}}
         dest=/etc/nginx/sites-enabled/{{config.stdout}}
         owner=root
         group=root
         state=link
   sudo: true

 - name: Open firewall for http
   shell: ufw allow http
   sudo: true

#   notify: restart nginx


