---
- name: Register content/theme directory
  command: echo "/srv/{{ wp_project_name }}/content"
  register: content_path

- name: Checkout theme base from REPO
  git: repo=git@github.com:tripl3inf/ten10_app.git dest="{{ content_path.stdout }}"
       version={{ theme_repo_branch | default (default_theme_branch) }}
       accept_hostkey=yes
       force=yes
#  sudo: true
#  sudo_user: "{{ deploy_user }}"

- name: Composer install
  shell: cd {{ content_path.stdout }}; composer install

- name: NPM install
  npm: path={{ content_path.stdout }}/themes/ten10_roots
       state=present

- name: Bower install
  shell: cd {{ content_path.stdout }}/themes/ten10_roots; bower install --silent

- name: Grunt build
  shell: cd {{ content_path.stdout }}/themes/ten10_roots; grunt build
  notify:
  - restart nginx
  - restart php-fpm

