---

- name: Get release timestamp
  command: date +%Y%m%d%H%M%S
  register: timestamp

- name: Name release directory
  command: echo "/srv/{{ wp_project_name }}/repo/{{ timestamp.stdout }}"
  register: release_path

- name: Checkout theme base from REPO
  git: repo={{ theme_repo_url }} dest={{ release_path.stdout }} version=wp_deploy accept_hostkey=yes
  sudo: false

- name: Composer install
  shell: cd {{ release_path.stdout }}; composer install

- name: Update to current
  file: >
    state=link
    path=/srv/{{ wp_project_name }}/content
    src={{ release_path.stdout }}
    force=yes
  sudo: true

- name: test php-fpm restart
  shell: service php5-fpm restart
  sudo: true
