---
- name: Register content/theme directory
  command: echo "/srv/{{ wp_project_name }}/content"
  register: content_path

- name: Checkout theme base from REPO
  git: repo={{ theme_repo_url }} dest=/srv/{{ wp_project_name }}/content
       version={{ theme_repo_branch | default (default_theme_branch) }}
       accept_hostkey=yes
  sudo: false
  notify:
  - restart nginx
  - restart php-fpm

#- name: Composer install
#  shell: cd {{ release_path.stdout }}; composer install
#
#- name: NPM install
#  npm: path=/{{ release_path.stdout }}/themes/ten10_roots
#       state=present
#       global=yes
#       production=yes

#- name: php-fpm restart
#  shell: service php5-fpm restart
#  sudo: true
