---

- name: Register theme directory
  command: "echo /srv/{{env}}/{{ wp_project_name }}/content/themes"
  register: theme_path

- name: Create WP theme directory
  file: path={{theme_path.stdout}}
        state=directory
        mode=0755
  register: theme

#- debug: var=content_path.path

- name: Checkout theme base from REPO
  git: repo={{theme_repo_url}} dest={{theme_path.stdout}}/{{theme_name}}
       accept_hostkey=yes
       force=yes
      # version={{theme_repo_branch|default(omit)}}
  sudo: false
#  sudo_user: "{{ deploy_user }}"


#- name: Composer install
#  shell: cd {{theme_path.stdout}}; composer install

- name: Build theme
  shell: cd {{theme_path.stdout}}/{{theme_name}}; {{ item }}
  ignore_errors: true
  with_items:
    - sudo npm install
    - bower install
    - grunt build
  sudo: false
  notify: restart php-fpm

- name: Wait to restart nginx
  pause: seconds=10
  notify: restart nginx




#- name: NPM install
#  npm: path=content_path.stdout/themes/ten10_roots
#       state=present
#
#- name: Bower install
#  shell: cd content_path.stdout/themes/ten10_roots; bower install --silent
#
#- name: Grunt build
#  shell: cd content_path.stdout/themes/ten10_roots; grunt build

