---
- name: Fetch random salts for Wordpress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
  sudo: false

- name: Create wp-config file
  template: src="template_wp-config" dest="/srv/{{ wp_project_name }}/wp-config.php"
  sudo: false

- name: Download WP core files
  command: wp core download --path="/srv/{{ wp_project_name }}/wordpress/"
  sudo: false
  ignore_errors: true

#- name: Link wp-config to current directory
#  file: src="/srv/{{ wp_project_name }}/shared/wp-config.php" dest="../current" state="link"
#  sudo: false

#- name: Link core files to current
#  command: "ln -sf /srv/{{ wp_project_name }}/shared/wordress /srv/{{ wp_project_name }}/current/wordpress"
#  tags:
#    - dbg

- name: WP installed?
  command: wp core is-installed --allow-root
  args:
    chdir: "/srv/{{ wp_project_name }}/wordpress"
  register: site_statuses
  ignore_errors: true




#- name: SSH | Find Git repo SSH host key
#  shell: ssh-keyscan {{ git_repo }}
#  register: git_repo_host_key
#  sudo_user: {{ deploy_user }}
#
#- name: SSH | Add Git repo host key to known_hosts file
#  lineinfile: create=yes dest=/home/prov/.ssh/known_hosts line='{{ git_repo_host_key.stdout }}' state=present
#  sudo_user: {{ deploy_user }}




- name: Install WP
  command: wp core install
           --allow-root
           --url="{{ wp_home_url }}"
           --title="{{ wp_project_name }}"
           --admin_user="{{ deploy_user }}"
           --admin_password="{{ wp_admin_pass }}"
           --admin_email="{{ wp_admin_email }}"
           --path="wordpress"
  args:
    chdir: "/srv/{{ wp_project_name }}"
  with_items: site_statuses.results
  notify: reload nginx