---
- name: Fetch random salts for Wordpress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
  sudo: false

- name: Create wp-config file
  template: src="template_wp-config.php" dest="/srv/{{ wp_project_name }}/wp-config.php"
  sudo: false

- name: Copy index.php file
  template: src="template_wp_index.php" dest="/srv/{{ wp_project_name }}/index.php"
  sudo: false

- name: Download WP core files
  command: wp core download --path="/srv/{{ wp_project_name }}/wordpress/"
  sudo: false
  ignore_errors: true
  register: wp_core_files

- name: WP installed?
  command: wp core is-installed --allow-root
  args:
    chdir: "/srv/{{ wp_project_name }}/wordpress"
  when: wp_core_files | changed
  register: site_status
  ignore_errors: true

- name: Install WP
  command: wp core install
           --allow-root
           --url="{{ wp_home_url }}"
           --title="{{ wp_project_name }}"
           --admin_user="{{ deploy_user }}"
           --admin_password="{{ wp_admin_pass }}"
           --admin_email="{{ wp_admin_email }}"
           --path="wordpress"
  args:
    chdir: "/srv/{{ wp_project_name }}"
  when: wp_core_files | changed
  notify:
    - restart nginx
    - restart php-fpm

