---
ansible_ssh_user: tripl3inf
#ansible_ssh_pass: vagrant


# ENVIRONMENT -- dev, staging, production
DEV: true
VBox: false

# deploy user credentials
sudoers_email: true
deploy_user: tripl3inf
deploy_group: t3i
deploy_key: "~/.ssh/t3i_deploy.pub"
deploy_passwd: "$6$1baYpoEoIHN0$uxzGipd9Tghmw2caXXbjwxWqXY9/iXtIRk/FylrN0XRYRun9GOmw6H0MGOWNFma1NNuBdXaxCIqtqVFBPg/l2."

# GitHub SSH Private Key
github_key: "~/.ssh/t3i_deploy"
github_key_name: t3i_deploy

### MySQL/MarinaDB Database
# override default root passwd (apps/defaults/)
sql_root_pass: "sql_pass"


# memcched session?
memcached_sessions: false

# wordpress
wp_project_name: wptest
wp_home_url: wptest.dev
wp_db_name: DB_wptest
wp_db_pass: test_passwd
wp_admin_pass: test_passwd
wp_admin_email: test@test.com

# Disable All Updates
auto_up_disable: true
