---

- name: Copy private SSH key to remote
  action: copy src={{ github_key }} dest=/home/{{ deploy_user }}/.ssh/{{ github_key_name }} owner={{ deploy_user }} mode=0600
#  remote_user: "{{ deploy_user }}"
#  sudo: false
  tags: github_key

- name: Copy public SSH key to remote
  action: copy src={{ github_key }} dest=/home/{{ deploy_user }}/.ssh/{{ github_key_name }}.pub mode=0600
  tags: github_key
