---
- name: Setup deploy group
  group: name={{ deploy_group }} state=present
  sudo: true

- name: Setup deploy user
  user: name={{ deploy_user }}
        group={{ deploy_group }}
        groups={{ deploy_groups }}
        shell=/bin/bash
        password={{ deploy_passwd }}
        state=present

- name: Add public key to server
  authorized_key: user={{ deploy_user }} key="{{ item }}"
  with_file: deploy_key

- name: Create tmp file for sudoers additions
  command: cp -f /etc/sudoers /etc/sudoers.tmp
  tags:

- name: Create sudoers file backup
  command: cp -f /etc/sudoers /etc/sudoers.{{ ansible_date_time.date }}_{{ ansible_date_time.time }}.bak
  sudo: true

- name: Sudoers | update sudoers file and validate
  lineinfile: "dest=/etc/sudoers.tmp line='{{ deploy_user }} ALL=(ALL) NOPASSWD: ALL' regexp='^{{deploy_user }}' state=present"
  sudo: true

- name: Set SSH-Agent environment var in sudoers
  lineinfile: >
    dest=/etc/sudoers.tmp
    state=present
    regexp='^Defaults env_keep\+\=SSH_AUTH_SOCK'
    line='Defaults env_keep+=SSH_AUTH_SOCK'
    insertafter='^Defaults'

- name: Check sudoers file and make current
  shell: visudo -q -c -f /etc/sudoers.tmp && cp -f /etc/sudoers.tmp /etc/sudoers
  sudo: true

- name: Delete server ssh keys and regenerate
  shell: rm -rf /etc/ssh/ssh_host_* ; dpkg-reconfigure openssh-server
  sudo: true
  notify: restart sshd

#- name: Re-generate server ssh keys
#  shell: dpkg-reconfigure openssh-server
#  sudo: true
#  notify: restart sshd


- name: Configure firewall for SSH
  ufw: rule=allow name=OpenSSH

- name: Enable firewall
  ufw: state=enabled

- name: Strict SSH access
  lineinfile: >
    dest=/etc/ssh/sshd_config
    state=present
    regexp='^#?{{ item.key }}'
    line='{{ item.key }} {{ item.value }}'
    validate='/usr/sbin/sshd -t -f %s'
  with_items:
    - { key: 'PermitRootLogin',        value: 'no'}
    - { key: 'PasswordAuthentication', value: 'no'}
    - { key: 'AllowGroups',            value: "{{deploy_group}}"}
    - { key: 'MaxAuthTries',           value: "5"}
    - { key: 'LoginGraceTime',         value: "60"}
    - { key: 'MaxSessions',            value: "5"}
    - { key: 'MaxStartups',            value: "10:30:60"}
  notify: restart sshd




#- include: github_key.yml

