---
- hosts: localhost
  connection: local
  serial: 1
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - include: tasks/droplet.yml

- hosts: newdroplets
  user: root      
  vars_files:
    - vars.yml
  tasks:
    - include: ../user/tasks/main.yml

  handlers:
    - include: handlers/site.yml
