# Install PHP Memcached

---
- name: Install PHP Memcached
  apt: name="{{ item }}" state=present force=yes
  with_items:
  - memcached
  - php5-memcache

- name: Copy the memcached client configuration file
  template: src=memcached.j2 dest=/etc/memcached.conf
  notify: restart memcached

- name: Set the max open file descriptors
  sysctl: name=fs.file-max value={{ memcached.fs_file_max }} state=present

- name: Start the memcached service
  service: name=memcached state=started enabled=yes