---
- hosts: all
  remote_user: vagrant
  sudo: true
  vars:
    web_server: nginxphp
  vars_files:
    - vars/mysql.yml
    - vars/common.yml
    - [ "vars/nginxphp.yml", "vars/ws_defaults.yml" ]
  roles:
    - init
    - nginx
    - php5-fpm
    - mariadb
    - composer
    - wp-cli
    - bcen01.nodejs
