- name: Deploy public key
  digital_ocean: >
    state=present
    command=ssh
    name=t3i_key
    client_id="{{ client_id }}"
    api_key="{{ api_key }}"
    ssh_pub_key="{{ my_pub_key }}"
  register: do_droplet
     
- name: Create Digital Ocean droplet 512Mb - Ubuntu 14.04 - NYC3
  digital_ocean: >
    state=present
    command=droplet
    name="{{ do_hostname }}"
    client_id="{{ client_id }}"
    api_key="{{ api_key }}"
    size_id=66
    ssh_key_ids="{{ do_droplet.ssh_key.id }}"
    region_id="{{region_id}}"
    image_id="{{image_id}}"
    wait_timeout=1200
  register: do_droplet

- debug: msg="ID is {{ do_droplet.droplet.id }}"
- debug: msg="IP is {{ do_droplet.droplet.ip_address }}"
    
- name: Add new droplet to inventory
  add_host: >
    name="{{ do_droplet.droplet.ip_address }}"
    groups=newdroplets
          
